version: 2.1
orbs:
  win: circleci/windows@2.4.1
parameters:
  lockindex:
    type: string
    default: '3'
jobs:
  Core:
    docker:
      - image: satantime/puppeteer-node:17.4.0-buster
    steps:
      - checkout
      - restore_cache:
          key: root-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "package-lock.json" }}
      - run:
          name: NPM Install
          command: |
            if [ ! -d "./node_modules/" ]; then
              npm ci --no-optional --ignore-scripts && \
              node ./node_modules/puppeteer/install.js && \
              npm run postinstall
            fi
      - save_cache:
          key: root-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - restore_cache:
          key: docs-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "docs/package-lock.json" }}
      - run:
          name: NPM Install
          command: |
            if [ ! -d "./docs/node_modules/" ]; then
              npm run ci:docs
            fi
      - save_cache:
          key: docs-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "docs/package-lock.json" }}
          paths:
            - ./docs/node_modules
      - run:
          name: Core Style
          command: ./node_modules/.bin/prettier -u -c .
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: TS Source
          command: ./node_modules/.bin/tsc --noEmit -p ./libs/ngrx-entity-relationship/tsconfig.lib.json
      - run:
          name: TS Spec
          command: ./node_modules/.bin/tsc --noEmit -p ./libs/ngrx-entity-relationship/tsconfig.spec.json
      - run:
          name: Tests
          command: npm run test -- --codeCoverage --reporters junit
      - run:
          name: Docs
          command: npm run build:docs
      - run:
          name: Build
          command: |
            npm run st:build
            cd ./dist/libs/ngrx-entity-relationship
            npm pack
            cd ..
            mv ./ngrx-entity-relationship/ngrx-entity-relationship-0.0.0.tgz ./
            rm -Rf ./ngrx-entity-relationship
            tar -xf ./ngrx-entity-relationship-0.0.0.tgz package
            rm ./ngrx-entity-relationship-0.0.0.tgz
            mv ./package ./ngrx-entity-relationship
            cd ../..
      - run:
          name: Collecting Coverage coveralls.io
          command: ./node_modules/.bin/coveralls < test-reports/coverage/lcov/lcov.info
      - run:
          name: Collecting Coverage codecov.io
          command: ./node_modules/.bin/codecov -f test-reports/coverage/lcov/lcov.info --disable=gcov
      - run:
          name: Collecting Coverage codeclimate.com
          command: |
            curl -sL https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 \
              > $HOME/codeclimate
            chmod +x $HOME/codeclimate
            $HOME/codeclimate before-build
            $HOME/codeclimate format-coverage \
              -t lcov test-reports/coverage/lcov/lcov.info \
              -o test-reports/codeclimate.json
            $HOME/codeclimate upload-coverage \
              -r cf49447c142f5bdfd06887571e5b339a8cbe7b2e4a527c6742e3dc0020b3374d \
              -i test-reports/codeclimate.json
      - store_test_results:
          path: ./test-reports
      - store_artifacts:
          path: ./test-reports/coverage
          prefix: coverage
      - persist_to_workspace:
          root: dist
          paths:
            - .
  'Install':
    docker:
      - image: satantime/puppeteer-node:17.4.0-buster
    steps:
      - checkout
      - restore_cache:
          key: a6-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a6/package-lock.json" }}
      - restore_cache:
          key: a7-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a7/package-lock.json" }}
      - restore_cache:
          key: a8-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a8/package-lock.json" }}
      - restore_cache:
          key: a9-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a9/package-lock.json" }}
      - restore_cache:
          key: a10-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a10/package-lock.json" }}
      - restore_cache:
          key: a11-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a11/package-lock.json" }}
      - restore_cache:
          key: a12-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a12/package-lock.json" }}
      - restore_cache:
          key: r7-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/r7/package-lock.json" }}
      - run:
          name: NPM Install
          command: |
            if [ ! -d "e2e/a6/node_modules/" ]; then
              npm run i:ci:a6
            fi
            if [ ! -d "e2e/a7/node_modules/" ]; then
              npm run i:ci:a7
            fi
            if [ ! -d "e2e/a8/node_modules/" ]; then
              npm run i:ci:a8
            fi
            if [ ! -d "e2e/a9/node_modules/" ]; then
              npm run i:ci:a9
            fi
            if [ ! -d "e2e/a10/node_modules/" ]; then
              npm run i:ci:a10
            fi
            if [ ! -d "e2e/a11/node_modules/" ]; then
              npm run i:ci:a11
            fi
            if [ ! -d "e2e/a12/node_modules/" ]; then
              npm run i:ci:a12
            fi
            if [ ! -d "e2e/r7/node_modules/" ]; then
              npm run i:ci:r7
            fi
      - save_cache:
          key: a6-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a6/package-lock.json" }}
          paths:
            - ./e2e/a6/node_modules
      - save_cache:
          key: a7-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a7/package-lock.json" }}
          paths:
            - ./e2e/a7/node_modules
      - save_cache:
          key: a8-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a8/package-lock.json" }}
          paths:
            - ./e2e/a8/node_modules
      - save_cache:
          key: a9-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a9/package-lock.json" }}
          paths:
            - ./e2e/a9/node_modules
      - save_cache:
          key: a10-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a10/package-lock.json" }}
          paths:
            - ./e2e/a10/node_modules
      - save_cache:
          key: a11-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a11/package-lock.json" }}
          paths:
            - ./e2e/a11/node_modules
      - save_cache:
          key: a12-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a12/package-lock.json" }}
          paths:
            - ./e2e/a12/node_modules
      - save_cache:
          key: r7-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/r7/package-lock.json" }}
          paths:
            - ./e2e/r7/node_modules
  'Angular 6':
    docker:
      - image: satantime/puppeteer-node:17.4.0-buster
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - restore_cache:
          key: a6-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a6/package-lock.json" }}
      - run:
          name: Spreading Build
          command: npm run s:a6
      - run:
          name: Spreading Tests
          command: npm run s:test:a6
      - run:
          name: UT
          command: npm run test:a6
      - run:
          name: E2E
          command: npm run e2e:a6
      - run:
          name: Build
          command: npm run b:a6
  'Angular 7':
    docker:
      - image: satantime/puppeteer-node:17.4.0-buster
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - restore_cache:
          key: a7-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a7/package-lock.json" }}
      - run:
          name: Spreading Build
          command: npm run s:a7
      - run:
          name: Spreading Tests
          command: npm run s:test:a7
      - run:
          name: UT
          command: npm run test:a7
      - run:
          name: E2E
          command: npm run e2e:a7
      - run:
          name: Build
          command: npm run b:a7
  'Angular 8':
    docker:
      - image: satantime/puppeteer-node:17.4.0-buster
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - restore_cache:
          key: a8-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a8/package-lock.json" }}
      - run:
          name: Spreading Build
          command: npm run s:a8
      - run:
          name: Spreading Tests
          command: npm run s:test:a8
      - run:
          name: UT
          command: npm run test:a8
      - run:
          name: E2E
          command: npm run e2e:a8
      - run:
          name: Build
          command: npm run b:a8
  'Angular 9 without Ivy':
    docker:
      - image: satantime/puppeteer-node:17.4.0-buster
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - restore_cache:
          key: a9-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a9/package-lock.json" }}
      - run:
          name: Spreading Build
          command: npm run s:a9
      - run:
          name: Spreading Tests
          command: npm run s:test:a9
      - run:
          name: UT
          command: npm run test:a9:off
      - run:
          name: E2E
          command: npm run e2e:a9:off
      - run:
          name: Build
          command: npm run b:a9:off
  'Angular 9 with Ivy':
    docker:
      - image: satantime/puppeteer-node:17.4.0-buster
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - restore_cache:
          key: a9-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a9/package-lock.json" }}
      - run:
          name: Spreading Build
          command: npm run s:a9
      - run:
          name: Spreading Tests
          command: npm run s:test:a9
      - run:
          name: UT
          command: npm run test:a9:on
      - run:
          name: E2E
          command: npm run e2e:a9:on
      - run:
          name: Build
          command: npm run b:a9:on
  'Angular 10 without Ivy':
    docker:
      - image: satantime/puppeteer-node:17.4.0-buster
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - restore_cache:
          key: a10-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a10/package-lock.json" }}
      - run:
          name: Spreading Build
          command: npm run s:a10
      - run:
          name: Spreading Tests
          command: npm run s:test:a10
      - run:
          name: UT
          command: npm run test:a10:off
      - run:
          name: E2E
          command: npm run e2e:a10:off
      - run:
          name: Build
          command: npm run b:a10:off
  'Angular 10 with Ivy':
    docker:
      - image: satantime/puppeteer-node:17.4.0-buster
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - restore_cache:
          key: a10-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a10/package-lock.json" }}
      - run:
          name: Spreading Build
          command: npm run s:a10
      - run:
          name: Spreading Tests
          command: npm run s:test:a10
      - run:
          name: UT
          command: npm run test:a10:on
      - run:
          name: E2E
          command: npm run e2e:a10:on
      - run:
          name: Build
          command: npm run b:a10:on
  'Angular 11 without Ivy':
    docker:
      - image: satantime/puppeteer-node:17.4.0-buster
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - restore_cache:
          key: a11-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a11/package-lock.json" }}
      - run:
          name: Spreading Build
          command: npm run s:a11
      - run:
          name: Spreading Tests
          command: npm run s:test:a11
      - run:
          name: UT
          command: npm run test:a11:off
      - run:
          name: E2E
          command: npm run e2e:a11:off
      - run:
          name: Build
          command: npm run b:a11:off
  'Angular 11 with Ivy':
    docker:
      - image: satantime/puppeteer-node:17.4.0-buster
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - restore_cache:
          key: a11-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a11/package-lock.json" }}
      - run:
          name: Spreading Build
          command: npm run s:a11
      - run:
          name: Spreading Tests
          command: npm run s:test:a11
      - run:
          name: UT
          command: npm run test:a11:on
      - run:
          name: E2E
          command: npm run e2e:a11:on
      - run:
          name: Build
          command: npm run b:a11:on
  'Angular 12 without Ivy':
    docker:
      - image: satantime/puppeteer-node:17.4.0-buster
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - restore_cache:
          key: a12-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a12/package-lock.json" }}
      - run:
          name: Spreading Build
          command: npm run s:a12
      - run:
          name: Spreading Tests
          command: npm run s:test:a12
      - run:
          name: UT
          command: npm run test:a12:off
      - run:
          name: E2E
          command: npm run e2e:a12:off
      - run:
          name: Build
          command: npm run b:a12:off
  'Angular 12 with Ivy':
    docker:
      - image: satantime/puppeteer-node:17.4.0-buster
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - restore_cache:
          key: a12-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/a12/package-lock.json" }}
      - run:
          name: Spreading Build
          command: npm run s:a12
      - run:
          name: Spreading Tests
          command: npm run s:test:a12
      - run:
          name: UT
          command: npm run test:a12:on
      - run:
          name: E2E
          command: npm run e2e:a12:on
      - run:
          name: Build
          command: npm run b:a12:on
  'React Redux 7':
    docker:
      - image: satantime/puppeteer-node:17.4.0-buster
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - restore_cache:
          key: r7-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "e2e/r7/package-lock.json" }}
      - run:
          name: Spreading Build
          command: npm run s:r7
      - run:
          name: UT
          command: npm run test:r7
      - run:
          name: Build
          command: npm run b:r7
  Core IE:
    executor:
      name: win/default
    steps:
      - checkout
      - restore_cache:
          key: root-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "package-lock.json" }}
      - run:
          name: NPM Install
          command: |
            if ((Test-Path "node_modules") -ne "True") {
              npm ci --no-optional --ignore-scripts
              npm run postinstall
            }
      - save_cache:
          key: root-<< pipeline.parameters.lockindex >>-{{ arch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Unit Tests
          command: npx nx run ngrx-entity-relationship:test:ie --reporters junit
      - store_test_results:
          path: ./test-reports
    environment:
      IE_BIN: 'C:\Program Files\Internet Explorer\iexplore.exe'
workflows:
  version: 2
  build:
    jobs:
      - Core
      - Install:
          requires:
            - Core
      - 'Core IE':
          requires:
            - Core
      - 'Angular 6':
          requires:
            - Install
      - 'Angular 7':
          requires:
            - Install
      - 'Angular 8':
          requires:
            - Install
      - 'Angular 9 without Ivy':
          requires:
            - Install
      - 'Angular 9 with Ivy':
          requires:
            - Install
      - 'Angular 10 without Ivy':
          requires:
            - Install
      - 'Angular 10 with Ivy':
          requires:
            - Install
      - 'Angular 11 without Ivy':
          requires:
            - Install
      - 'Angular 11 with Ivy':
          requires:
            - Install
      - 'Angular 12 without Ivy':
          requires:
            - Install
      - 'Angular 12 with Ivy':
          requires:
            - Install
      - 'React Redux 7':
          requires:
            - Install
